Repository dotnet/csharpstandard, pull requests merged in 2024-12, with the labels that each got.

#1223 Add Missing Subsection, General, to 9.2.9 "Local variables"
  standard/expressions.md
  standard/patterns.md
  standard/variables.md
Labels: type: formatting

#1225 Add more NRT examples
  standard/types.md
Labels: meeting: discuss

#1226 The compiler -> a compiler
  standard/attributes.md
  standard/basic-concepts.md
  standard/classes.md
  standard/conversions.md
  standard/expressions.md
  standard/interfaces.md
  standard/lexical-structure.md
  standard/standard-library.md
  standard/statements.md
  standard/variables.md
Labels: meeting: discuss

#1211 Remove constraints on stackalloc (support new locations)
  standard/expressions.md
  standard/unsafe-code.md
Labels: meeting: discuss, Review: pending

#1120 Correct 2 x grammar rules for compilation unit name in #line
  standard/lexical-structure.md
Labels: type: bug, meeting: discuss

#604 remove prohibition of unmanaged constructed types
  standard/types.md
Labels: meeting: discuss, type: feature, Review: pending
