Repository dotnet/csharpstandard, pull requests merged in 2024-03, with the labels that each got.

#1061 Minor nit: make sentence a new para
  standard/classes.md
Labels: type: formatting

#1063 Fix examples where feasible
  standard/classes.md
  standard/lexical-structure.md
  standard/statements.md
  tools/ExampleTester/GeneratedExample.cs
  tools/example-templates/additional-files/PartialClass1ForSwitch.cs
  tools/example-templates/additional-files/PartialProgramForSwitch.cs
  tools/example-templates/additional-files/PartialProgramWithFGxy.cs
  tools/example-templates/code-in-class-lib/Library.cs
  tools/example-templates/code-in-main-without-using/Program.cs
  tools/example-templates/code-in-main/Program.cs
Labels: meeting: discuss

#1054 Tweak CLI wording
  standard/introduction.md
Labels: meeting: discuss

#869 Add support for static local functions
  standard/statements.md
Labels: meeting: discuss, type: feature, Review: pending, seQUESTered
